measurements:
  - name: short-measurement
    client:
        host: 127.0.0.1
        port: 5000
    turncat:
      log: "all:INFO"
      # Other info is gathered by the go script
    loadGenerator: 
      command: iperf
      args: ["-c", "localhost", "-p", "5000", "-u", "-i", "1", "-l", "100", "-b", "800000", "-t", "100", "-e"]
    queries:
      - name: cpu-usage
        query: sum(rate(container_cpu_usage_seconds_total[5m])) by (namespace)
      - name: memory-usage
        query: sum(container_memory_working_set_bytes) by (namespace) / 1024 / 1024 / 1024